MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "/raid/Lei_Data/000Result/0Model_ImageNet/IterNorm_org/resnet50/resnet_whiten_3n50_GN_NG64_No_sgd_lr0.1_step_wd0.0001_dr0/best.pth"
  WHITENING:
    DIM_PER_GP: 0
    NUM_GROUPS: 64
    T: 5
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False  #set as False for pre-trained pytorch model
    DF: 'No'
    TRANS_FUNC: "Bottleneck_3n_WithGN_FT"
    STEM_FUNC: "StemWithGN"
  FPN:
    USE_GN: 'GN'
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    USE_GN: 'GN'
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    CONV_HEAD_DIM: 256
    NUM_STACKED_CONVS: 4
    FEATURE_EXTRACTOR: "FPNXconv1fcFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  TO_BGR255: False
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "./set_result/e2e_faster_rcnn_R_50_0selfStep3nGN_1FPNGn_2XconvGn_1x/"
